# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet {{C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.runs/xadc_wiz_1_synth_1/xadc_wiz_1.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.runs/xadc_wiz_1_synth_1/xadc_wiz_1.dcp}}]
read_vhdl -library xil_defaultlib {
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/imports/new/count20.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/imports/new/binary2sevseg.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/imports/new/ram8x6.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/imports/new/decoder3to8.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/new/PWM.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/new/DisplayController.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/new/ADC_Controller.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/new/B2BCD.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/imports/new/DisplayInterface.vhd}
  {C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/new/TOP.vhd}
}
read_xdc {{C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc}}]

synth_design -top TOP -part xc7a100tcsg324-1
write_checkpoint -noxdef TOP.dcp
catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
