# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/ip/xadc_wiz_1_1/xadc_wiz_1.xci
# IP: The module: 'xadc_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/ip/xadc_wiz_1_1/xadc_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/ip/xadc_wiz_1_1/xadc_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/ip/xadc_wiz_1_1/xadc_wiz_1.xci
# IP: The module: 'xadc_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/ip/xadc_wiz_1_1/xadc_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/David Amin/Documents/ECE 414/414L/project_2/project_2.srcs/sources_1/ip/xadc_wiz_1_1/xadc_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
